### ISSUE TITLE
Mismatch in apache-arrow versions in dev / peer deps

### ISSUE THREAD

**Issue by fspoettel** [kylebarron/arrow-js-ffi#47]
Hey! Thank you for this library.

I noticed that there is a mismatch in major versions for the `apache-arrow` dependency.

The `peerDependencies` specify `^10`:

https://github.com/kylebarron/arrow-js-ffi/blob/9ea5dfae4b745518389ae635bfd6e52553df95fd/package.json#L32

while the `devDependencies` specify `^12`:

https://github.com/kylebarron/arrow-js-ffi/blob/9ea5dfae4b745518389ae635bfd6e52553df95fd/package.json#L38

**Comment by kylebarron** [comment]
Maybe it's misguided, but it was intentional to say "this should work with many recent Arrow versions, but for my own tests I'll test on the most recent version of Arrow (though v13 was released lately). I haven't actually tested what's the most recent version that will work with this, but it's probably safest to bump the peer dependency up to the latest (assuming that anyone using this is somewhat bleeding-edge). 

Arrow v14 will have a couple fixes for different data types, so when that's released I'll definitely bump the requirement to 14

**Comment by fspoettel** [comment]
Thanks for the quick reply! In that case, it might make sense to use a version range like `>=10` (any version above 10.0.0) or `>=10 <13` (any version between 10.0.0 and 12.x.x).

The `^` locks to one specific major version, which results in peer dependency warnings when you try to install the package alongside `apache-arrow@^12`.

```
npm WARN Found: apache-arrow@10.0.1
npm WARN node_modules/apache-arrow
npm WARN   apache-arrow@"^12.0.0" from the root project
npm WARN   1 more (arrow-js-ffi)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer apache-arrow@"^10.0.0" from arrow-js-ffi@0.3.0
npm WARN node_modules/arrow-js-ffi
npm WARN   arrow-js-ffi@"^0.3.0" from the root project
```

**Comment by kylebarron** [comment]
yeah I'm happy to do that! Maybe ironic that I enjoy low-level JS/Wasm work, but I'm so bad at bundling and JS/TS project setup. So suggestions are welcomed!

Maybe best for now to set `>=12`? (The Arrow project is kinda annoying in that it pins all versions across all language implementations together, so most of the time there are no breaking changes in the JS implementation, but always a major version bump)

**Comment by fspoettel** [comment]
Hey, thanks for the fix, appreciate it! The implemented fix works for me. If you want to keep backwards-compat. so that this can be adopted w/o downstream issues, you could also set something like `>=10 <=14` to indicate all versions between `10.0.0` and `13.x.x`.

 Looking forward to this being released!
